### ISSUE TITLE
Update secret variable names

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/HTAN-data-curator#34]
It looks like that in merging #33 some of the secret names have changed.

![Screenshot 2022-10-13 at 16 51 02](https://user-images.githubusercontent.com/14945787/195645630-a98a099a-37ce-4bdf-ac6d-e378b2ac8e23.jpg)

**Comment by adamjtaylor** [comment]
FYI @milen-sage - are the secrets we need to update/change documented somewhere?

**Comment by milen-sage** [comment]
@adamjtaylor I think[ this section ](https://github.com/Sage-Bionetworks/data_curator/blob/main/shinyapps_deploy.md#add-github-secrets) might help. @rrchai do you think GITHUB_TOKEN doc belongs there?

**Comment by milen-sage** [comment]
The above is linked from the main docs' [deployment section](https://github.com/Sage-Bionetworks/data_curator#deployment).  The deployment section mainly describes how to setup CI/CD so all the steps should already be taken care off in thet upstream repo from the point of view of downstream forks. But I see how it's relevant, and perhaps needs to be extended for more detail, for situations when changes are made in the CI/CD process and those need to be validated downstream by projects.

I personally am looking forward for the single multi-tenant instance of DCA so that projects no longer need to take care of updates. We are working on that and should have a version by Nov 3 (we'll have one for testing mid-Nov).

**Comment by rrchai** [comment]
@adamjtaylor You should be able to access the `GITHUB_TOKEN` without adding it to the secret.

see [this pr](https://github.com/Sage-Bionetworks/data_curator/pull/398)

**Comment by rrchai** [comment]
> do you think GITHUB_TOKEN doc belongs there?

@milen-sage it looks like the doc has not been updated with the `GITHUB_TOKEN` yet

**Comment by adamjtaylor** [comment]
I'm happy we can now close this with no required actions
